extraArgs:
  skip-nodes-with-system-pods: "false"
  skip-nodes-with-local-storage: "false"

rbac:
  create: true
  pspEnabled: false

autoDiscovery:
  enabled: true

priorityClassName: system-cluster-critical
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi
