alertmanager:
  service:
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\ncertmanager.k8s.io/cluster-issuer: letsencrypt-prod"

  resources:
     limits:
       cpu: 10m
       memory: 32Mi
     requests:
       cpu: 10m
     memory: 32Mi

server:
  enableAdminApi: true

  service:
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\ncertmanager.k8s.io/cluster-issuer: letsencrypt-prod"
      fabric8.io/ingress.name: prometheus

  resources:
     limits:
       cpu: 500m
       memory: 1Gi
     requests:
       cpu: 500m
       memory: 512Mi
