alertmanager:
  service:
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

  resources:
     limits:
       cpu: 10m
       memory: 32Mi
     requests:
       cpu: 10m
     memory: 32Mi

server:
  enableAdminApi: true

  service:
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
      fabric8.io/ingress.name: prometheus

  resources:
     limits:
       cpu: 500m
       memory: 1Gi
     requests:
       cpu: 500m
       memory: 512Mi
